services:

    mdenet-educationplatform:
        image: mdenet-educationplatform:latest
        ports:
            - "8080:80"
        build:
          context: educationplatform
          dockerfile: ./platform/Dockerfile
        
        volumes:
            - ./config/list-redirect.conf:/etc/nginx/conf.d/default.conf
            - ./public/list.html:/usr/share/nginx/html/list.html

    mdenet-tokenserver:
        image: mdenet-tokenserver:latest
        build:
          context: educationplatform
          dockerfile: ./tokenserver/Dockerfile
        ports:
            - "${TS_PORT}:${TS_PORT}"
        environment:
            - TS_PORT

    mdenet-test-activities:
        image: "nginx:1.23"
        ports:
            - "8082:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
            - ./activities:/usr/share/nginx/html

    mdenet-tool-epsilon:
        image: mdenet-tool-epsilon:latest
        ports:
            - "8070:80"
        build:
          context: platformtools
          dockerfile: static.epsilon/Dockerfile

    mdenet-tool-emfatic:
        image: mdenet-tool-emfatic:latest
        ports:
            - "8071:80"
        build:
          context: platformtools
          dockerfile: static.emfatic/Dockerfile

    mdenet-tool-ocl:
        image: mdenet-tool-ocl:latest
        ports:
            - "8072:80"
        build:
          context: platformtools
          dockerfile: static.ocl/Dockerfile

    mdenet-tool-emf:
        image: mdenet-tool-emf:latest
        ports:
            - "8073:80"
        build:
          context: platformtools
          dockerfile: static.emf/Dockerfile
          
    mdenet-tool-xtext:
      image: mdenet-tool-xtext-service:latest
      ports: 
          - 8074:8080
          - 10001:10001
          - 9000:9000
      build:
          context: platformtools
          dockerfile: xtext/Dockerfile
          
          
