name: build

on:
  push:
    branches:
      - 5-software-build-infrastructure-cicd

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Docker build and run
        run : docker compose up --build -d
  
      - name: Sleep for 30 seconds
        if: contains( ${{ matrix.os }}, 'ubuntu' )
        run: sleep 30s
        shell: bash
  
      - name: Sleep for 30 seconds
        if: contains( ${{ matrix.os }}, 'windows' )
        run: Start-Sleep -s 30
        shell: powershell

      - name: Stop the platform
        if: always()
        run: docker compose down
        
